repos:
  - repo: local
    hooks:
      - id: check-effective-bundles
        name: check-effective-bundles
        entry: /usr/bin/env
        args: [cascgen, pre-commit]
        language: script
        pass_filenames: false
        verbose: false
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        files: .*\.(yaml|yml)$